<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1240" started-at="2015-06-05T19:59:15Z" finished-at="2015-06-05T19:59:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1240" started-at="2015-06-05T19:59:15Z" finished-at="2015-06-05T19:59:17Z">
      <class name="com.practice.itunesapi.ItunesServiceTest">
        <test-method status="PASS" signature="validateBadRequest()[pri:0, instance:com.practice.itunesapi.ItunesServiceTest@52988584]" name="validateBadRequest" duration-ms="830" started-at="2015-06-05T12:59:15Z" finished-at="2015-06-05T12:59:16Z">
          <exception class="com.practice.itunesapi.ItunesServiceException">
            <message>
              <![CDATA[Service returned Failure Status Code]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.practice.itunesapi.ItunesServiceException: Service returned Failure Status Code
	at com.practice.itunesapi.ItunesServiceInvoker.invokeService(ItunesServiceInvoker.java:79)
	at com.practice.itunesapi.ItunesServiceInvoker.invoke(ItunesServiceInvoker.java:47)
	at com.practice.itunesapi.ItunesServiceTest.validateBadRequest(ItunesServiceTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.practice.itunesapi.ItunesServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBadRequest -->
        <test-method status="PASS" signature="validateInput()[pri:0, instance:com.practice.itunesapi.ItunesServiceTest@52988584]" name="validateInput" duration-ms="0" started-at="2015-06-05T12:59:16Z" finished-at="2015-06-05T12:59:16Z">
          <exception class="com.practice.itunesapi.ItunesInputValidationException">
            <message>
              <![CDATA[Search Term cannot be NULL]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.practice.itunesapi.ItunesInputValidationException: Search Term cannot be NULL
	at com.practice.itunesapi.ItunesServiceInvoker.validateInput(ItunesServiceInvoker.java:107)
	at com.practice.itunesapi.ItunesServiceInvoker.invoke(ItunesServiceInvoker.java:43)
	at com.practice.itunesapi.ItunesServiceTest.validateInput(ItunesServiceTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.practice.itunesapi.ItunesInputValidationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInput -->
        <test-method status="PASS" signature="validateResponse()[pri:0, instance:com.practice.itunesapi.ItunesServiceTest@52988584]" name="validateResponse" duration-ms="370" started-at="2015-06-05T12:59:16Z" finished-at="2015-06-05T12:59:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponse -->
      </class> <!-- com.practice.itunesapi.ItunesServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
